# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-03-04 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user1', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated',
            field=models.DateField(blank=True),
        ),
    ]
